name: todolist_app_android
description: A description of your project

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  excel: ^2.1.0
  file_picker: ^5.2.11
  path_provider: ^2.1.1
  file_saver: ^latest_version
  intl: ^0.18.0